# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1592, 1053)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(1390, 940, 151, 51))
        self.loadButton.setObjectName("loadButton")
        self.originImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.originImageLabel.setGeometry(QtCore.QRect(30, 30, 651, 471))
        self.originImageLabel.setStyleSheet("border-color: rgb(0, 0, 0);border-width: 1.2px; border-style: inset")
        self.originImageLabel.setText("")
        self.originImageLabel.setObjectName("originImageLabel")
        self.resultImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultImageLabel.setGeometry(QtCore.QRect(710, 30, 651, 471))
        self.resultImageLabel.setStyleSheet("border-color: rgb(0, 0, 0);border-width: 1.2px; border-style: inset")
        self.resultImageLabel.setText("")
        self.resultImageLabel.setObjectName("resultImageLabel")
        self.plotAngleLabel = QtWidgets.QLabel(self.centralwidget)
        self.plotAngleLabel.setGeometry(QtCore.QRect(710, 530, 651, 471))
        self.plotAngleLabel.setStyleSheet("border-color: rgb(0, 0, 0);border-width: 1.2px; border-style: inset")
        self.plotAngleLabel.setText("")
        self.plotAngleLabel.setObjectName("plotAngleLabel")
        self.plotMagnitudeLabel = QtWidgets.QLabel(self.centralwidget)
        self.plotMagnitudeLabel.setGeometry(QtCore.QRect(30, 530, 651, 471))
        self.plotMagnitudeLabel.setStyleSheet("border-color: rgb(0, 0, 0);border-width: 1.2px; border-style: inset")
        self.plotMagnitudeLabel.setText("")
        self.plotMagnitudeLabel.setObjectName("plotMagnitudeLabel")
        self.calculateButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateButton.setGeometry(QtCore.QRect(1390, 860, 151, 51))
        self.calculateButton.setObjectName("calculateButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1592, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate"))

    def loadImage(self):
        import tkinter as tk
        from tkinter import filedialog
        from PyQt5.QtGui import QPixmap
        from PyQt5.QtCore import Qt
        import cv2
        root = tk.Tk()
        root.withdraw()
        root.attributes('-topmost', True)
        path = filedialog.askopenfilename()
        if path != "":
            self.path = path
            self.image = cv2.imread(self.path)
            self.originImageLabel.setPixmap(QPixmap(self.path))
            self.originImageLabel.setScaledContents(True)
            self.originImageLabel.setAlignment(Qt.AlignCenter)

    def calculate(self):
        from imageProcessing import imageProcessing
        from plot import plotResult, drawImage
        from PyQt5.QtGui import QPixmap
        from PyQt5.QtCore import Qt
        import matplotlib.pylab as plt
        import numpy as np
        import cv2

        try:
            image = self.image
        except:
            return

        light = int(self.path.split("/")[-2].split("Bri")[-1])
        imageType = self.path.split("/")[-1].split(".png")[-2][-1]
        # print(light, imageType)

        data = imageProcessing(image, light, imageType)
        canny, drawContour, cropResizeImage = data["image"]
        Gradient, magnitude, angle, contour = data["result"]
        # drawImage(canny, "canny")
        # drawImage(threshold, "threshold")
        # drawImage(drawContour, "contour")
        # cv2.waitKey(0)
        # cv2.destroyAllWindows()

        for index in range(len(Gradient)):
            Gradient[index] += (int(index),)
        candidate = np.array(sorted(Gradient, key = lambda x: abs(abs(x[0]) - abs(x[1])))[:5])
        candidate = np.array(candidate, int)
        angle = np.array(angle)

        path = self.path.split("cal_")[-2]

        Gradient = np.array(Gradient)
        plotResult("Gradient", "index of point", "Gradient", "Gx", np.abs(Gradient[:, 0]))
        plotResult("Gradient", "index of point", "Gradient", "Gy", np.abs(Gradient[:, 1]))
        plt.savefig(path + "Gradient.png")
        plt.clf()

        plotResult("magnitude", "index of point", "magnitude", "magnitude", magnitude)
        plt.savefig(path + "magnitude.png")
        plt.clf()

        plotResult("Angle", "index of point", "degree", "Angle", angle)
        plt.plot(candidate[:, 2], angle[candidate[:, 2]], "o", label = "candidate")
        plt.savefig(path + "Angle.png")
        plt.clf()

        angle_dev = angle[1:] - angle[:-1]
        plotResult("Angle_dev", "index of point", "degree", "Angle_dev", angle_dev)
        plt.plot(candidate[:, 2], angle_dev[candidate[:, 2]], "o", label = "candidate")
        plt.savefig(path + "Angle_dev.png")
        plt.clf()

        self.resultImageLabel.setPixmap(QPixmap(path + "Gradient.png"))
        self.resultImageLabel.setScaledContents(True)
        self.resultImageLabel.setAlignment(Qt.AlignCenter)

        self.plotMagnitudeLabel.setPixmap(QPixmap(path + "magnitude.png"))
        self.plotMagnitudeLabel.setAlignment(Qt.AlignCenter)
        self.plotAngleLabel.setPixmap(QPixmap(path + "Angle.png"))
        self.plotAngleLabel.setAlignment(Qt.AlignCenter)

        path = self.path.split(".png")[0] + "_result.png"
        point = contour[candidate[0][2]]
        rad = 5
        cv2.line(drawContour, (point[0] - rad , point[1] - rad), (point[0] + rad, point[1] + rad), (255, 0, 0), 2)
        cv2.line(drawContour, (point[0] - rad , point[1] + rad), (point[0] + rad, point[1] - rad), (255, 0, 0), 2)
        # for index in range(1, len(candidate)):
        #     point = contour[candidate[index][2]]
        #     cv2.line(drawContour, (point[0], point[1]), (point[0], point[1]), (255, 0, 0), 5) 

        cv2.imwrite(path, drawContour)
        self.image = cv2.imread(path)
        self.originImageLabel.setPixmap(QPixmap(path))
        self.originImageLabel.setScaledContents(True)
        self.originImageLabel.setAlignment(Qt.AlignCenter)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
